name: Publish Firefox Add-on

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      ADDON_SOURCE_DIR: .
      ADDON_XPI_FILE: addon.xpi

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip and Rename Add-on
        run: |
          echo "Zipping add-on source from '${{ env.ADDON_SOURCE_DIR}}' into '${{ env.ADDON_XPI_FILE }}'..."

          # Change directory into the source directory to ensure correct archive structure (manifest.json at root)
          pushd ${{ env.ADDON_XPI_FILE }}

          # Create the XPI file directly in the GitHub workspace root ($GITHUB_WORKSPACE)
          # We use ./* to include all files and directories within the source directory.
          # -r ensures recursive zipping.
          zip -r $GITHUB_WORKSPACE/${{ env.ADDON_XPI_FILE }} ./*

          # Change back to the original directory
          popd

          echo "${{ env.ADDON_XPI_FILE }} created successfully."

          # Optional: List files in the workspace root to verify the created file
          ls $GITHUB_WORKSPACE/

      - name: Publish Firefox Add-on
        uses: wdzeng/firefox-addon@v1.2.0
        with:
          # Point the action to the XPI file we just created
          addon-guid: gamedownloader@github.com.cloudwaddie
          xpi-path: ${{ github.workspace }}/${{ env.ADDON_XPI_FILE }}
          jwt-issuer: ${{ secrets.AMO_JWT_ISSUER }}
          jwt-secret: ${{ secrets.AMO_JWT_SECRET }}
